EShop/Controllers/CandyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EShop.Models;
using EShop.Services.IRepository;
using EShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EShop.Controllers
{
    public class CandyController : Controller
    {
        private readonly ICandyRepository _candyRepository;
        private readonly ICategoryRepository _categoryRepository;

        public CandyController(ICandyRepository candyRepository, ICategoryRepository categoryRepository)
        {
            _candyRepository = candyRepository;
            _categoryRepository = categoryRepository;
        }

        //
        //public IActionResult List()
        public ViewResult List(string category)
        {
            //1
            //return View(_candyRepository.GetAllCandy); 

            //2
            //var candyListViewModel = new CandyListViewModel();
            //candyListViewModel.Candies = _candyRepository.GetAllCandy;
            //candyListViewModel.CurrentCategory = "BestSellers";
            //return View(candyListViewModel);

            //3
            IEnumerable<m_cls_Candy> candies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            }
            else
            {
                candies = _candyRepository.GetAllCandy.Where(c => c.Category.CategoryName == category);

                currentCategory = _categoryRepository.GetAllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory
            });


        }

        //
        public IActionResult Details(int id)
        {
            var candy = _candyRepository.GetCandyById(id);
            if (candy == null)
                return NotFound();

            return View(candy);
        }

        //
    }
}

EShop/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EShop.Controllers
{
    public class ContactController : Controller
    {
        //


        public IActionResult Index()
        {
            return View();
        }

        //
    }
}

EShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EShop.Services;
using EShop.Services.IRepository;
using EShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ICandyRepository _candyRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(ICandyRepository candyRepository, ShoppingCart shoppingCart)
        {
            _candyRepository = candyRepository;
            _shoppingCart = shoppingCart;
        }

        //
        public ViewResult Index()
        {
            _shoppingCart.ShoppingCartItems = _shoppingCart.GetShoppingCartItems();

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        //
        public RedirectToActionResult AddToShoppingCart(int candyId)
        {
            var selectedCandy = _candyRepository.GetAllCandy.FirstOrDefault(c => c.CandyId == candyId);

            if (selectedCandy != null)
            {
                _shoppingCart.AddToCart(selectedCandy, 1);
            }

            return RedirectToAction("Index");
        }

        //
        public RedirectToActionResult RemoveFromShoppingCart(int candyId)
        {
            var selectedCandy = _candyRepository.GetAllCandy.FirstOrDefault(c => c.CandyId == candyId);

            if (selectedCandy != null)
            {
                _shoppingCart.RemoveFromCart(selectedCandy);
            }

            return RedirectToAction("Index");
        }

        //
        public RedirectToActionResult ClearCart()
        {
            _shoppingCart.ClearCart();
            return RedirectToAction("Index");
        }

        //
    }
}

EShop/Views/Shared/_CandyCard.cshtml
@model m_cls_Candy

<div class="card">

	<img class="card-img-top" src="@Model.ImageThumbnailUrl" alt="image for candy shop" />
	<div class="card-body">
		<h4 class="card-title">@Model.Name</h4>
		<p class="card-text">@Model.Price.ToString("c")</p>
		<a class="card-link" asp-controller="Candy" asp-action="Details" asp-route-id="@Model.CandyId">See Detail</a>
	</div>
	<div class="addToCart">
		<p class="button">
			<a class="btn btn-primary"
			   asp-controller="ShoppingCart"
			   asp-action="AddToShoppingCart"
			   asp-route-candyId="@Model.CandyId">Add to Cart</a>
		</p>
	</div>

</div>

EShop/Views/Shared/_Carousel.cshtml
@*<div class="row carousel-holder">
	<div class="col-md-12">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
				<div class="item active">
					<img class="slide-image" src="~/Images/carousel1.jpg" alt="">
				</div>
				<div class="item">
					<img class="slide-image" src="~/Images/carousel2.jpg" alt="">
				</div>
				<div class="item">
					<img class="slide-image" src="~/Images/carousel3.jpg" alt="">
				</div>
			</div>
			<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
	</div>
</div>*@

<div id="myCarousel" class="carousel slide" data-ride="carousel">

	<!-- Indicators -->
	<ul class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	</ul>

	<!-- The slideshow -->
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img src="~/Images/carousel1.jpg" alt="" width="1100" height="400">
		</div>
		<div class="carousel-item">
			<img src="~/Images/carousel2.jpg" alt="" width="1100" height="400">
		</div>
		<div class="carousel-item">
			<img src="~/Images/carousel3.jpg" alt="" width="1100" height="400">
		</div>
	</div>

	<!-- Left and right controls -->
	<a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
		<span class="carousel-control-prev-icon"></span>
	</a>
	<a class="carousel-control-next" href="#myCarousel" data-slide="next">
		<span class="carousel-control-next-icon"></span>
	</a>
</div>

EShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
	<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

	<link href="~/content/site.css" rel="stylesheet" />
	<title>Candy Shop (EShop)</title>
</head>
<body>
	<div class="container">

		@*Nav*@
		<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="#">Navbar</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
					</li>
					@*<li class="nav-item">
						<a class="nav-link" asp-controller="Candy" asp-action="List">All Candy</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Pricing</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Dropdown link
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<a class="dropdown-item" href="#">Action</a>
							<a class="dropdown-item" href="#">Another action</a>
							<a class="dropdown-item" href="#">Something else here</a>
						</div>
					</li>*@
					<li class="nav-item">
						<a class="nav-link" asp-controller="Contact" asp-action="Index">Contact</a>
					</li>
					<li class="nav-item dropdown">
						@await Component.InvokeAsync("CategoryMenu")
					</li>
					<li class="nav-item">
						@await Component.InvokeAsync("ShoppingCartSummary")
					</li>

					<partial name="_LoginPartial" />

				</ul>
			</div>
		</nav>
		@*Nav*@

		<div class="row">
			<div class="col-sm-4">
				<p class="lead">
					<img class="img-responsive" src="~/Images/candyshoplogo.png" />
				</p>
			</div>
			<div class="col-sm-8">
				@RenderBody()


			</div>
		</div>

		@RenderSection("Scripts", required: false)

	</div>
</body>
</html>